# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: tammy makes things
email: tammy@tammymakesthings.com
description: >- # this means to ignore newlines until "baseurl:"
  making, electronics, CircuitPython, Python, programming, data geekery,
  technical musings, and random snark.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tammymakesthings.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  tammymakesthings
markdown: GFM

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-sitemap
minima:
  skin: dark
  header_pages:
    about.md
    projects.md
    contact.md
  date_format: "%Y-%m-%d"
  author:
    name: tammy cravit
    email: "tammy@tammymakesthings.com"
  social_links:
    - { platform: github,  user_url: "https://github.com/tammymakesthings" }
    - { platform: mastodon, user_url: "https://techhub.social/@tammymakesthings" }
