name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master
      - main
      - gh-pages

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out latest updates
        uses: actions/checkout@v2

      - name: Cache Ruby Gems
        uses: actions/cache@v1
        with:
          path: vendor/gems
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
  
      - name: Build and Deploy to GitHub Pages
        uses: DavidS/jekyll-deploy@main
        env:
          JEKYLL_ENV: production
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
      
